server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: userservice
  # nacos
  cloud:
    nacos:
      server-addr: localhost:8848
      discovery:
        cluster-name: beijing
mybatis:
#  type-aliases-package: cn.itcast.user.pojo
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS


# eureka configuration

#eureka:
#  client:
#    service-url:
#      defaultZone: http://127.0.0.1:10086/eureka

#userservice: # 给某个微服务配置负载均衡规则，这里是userservice服务
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule # 负载均衡规则 也可以通过将java config 配置

# ribbon eager load

#ribbon:
#  eager-load:
#    enabled: true
#    clients: userservice
